GET http://127.0.0.1:3003/user

###
POST http://127.0.0.1:3003/user
Content-Type: application/json

{
    "firstName": "Demo14",
    "lastName": "Demo14",
    "email": "demo14@example.com"
}

###
DELETE  http://127.0.0.1:3003/user/4


###
DELETE http://127.0.0.1:3003/user


###
GET http://127.0.0.1:3003/orderuser